// svelte-astro/src/components/skill.svelte
<script lang="ts">
  import GlassButton, {
    type GlassButtonProps,
  } from "@/components/glass-button.svelte";

  let { size, children }: GlassButtonProps = $props();

  let isClicked = $state(false);
</script>

<GlassButton
  className={isClicked ? "bg-gray-800 hover:bg-gray-700" : ""}
  onclick={() => (isClicked = !isClicked)}
  {size}
>
  {@render children?.()}
</GlassButton>

// react-astro/src/components/skill.tsx
import { type VariantProps } from "class-variance-authority";
import { useEffect, useState } from "react";

import GlassButton, { glassButtonVariants } from "@/components/glass-button";
import { toastAchievement } from "@/lib/utils";
import {
  decrementClickedSkillsCount,
  incrementClickedSkillsCount,
  registerSkill,
} from "@/store/clickedSkillsCount";

const Skill = ({
  children,
  size,
}: React.PropsWithChildren & VariantProps<typeof glassButtonVariants>) => {
  const [isClicked, setIsClicked] = useState<boolean>(false);

  const onAchievementFinish = (): void => {
    toastAchievement("click-all-skills");
  };

  useEffect(() => {
    registerSkill();
  }, []);

  return (
    <GlassButton
      className={isClicked ? "bg-gray-800 hover:bg-gray-700" : ""}
      onClick={() =>
        setIsClicked((prev) => {
          const isClicked = !prev;
          if (isClicked) {
            incrementClickedSkillsCount(onAchievementFinish);
          } else {
            decrementClickedSkillsCount();
          }
          return isClicked;
        })
      }
      size={size}
    >
      {children}
    </GlassButton>
  );
};

export default Skill;
