// react-astro/src/components/main/technologies.tsx
import { techStack } from "@/lib/tech-stack";
import styles from "./Main.module.css";

function Technologies() {
  return (
    <section className={styles.section}>
      <h2 className={styles.sectionHeading}>Technologies</h2>
      {Object.entries(techStack).map(([category, technologies]) => (
        <div className="flex flex-col gap-2" key={category}>
          <h3 className="min-w-30 font-semibold">{category}</h3>
          <div className="flex flex-wrap gap-2">
            {technologies.map((Technology, index) => (
              // biome-ignore lint/suspicious/noArrayIndexKey: list is fixed
              <Technology key={index} />
            ))}
          </div>
        </div>
      ))}
    </section>
  );
}

export { Technologies };

// svelte-astro/src/components/main/technologies.svelte
<script>
  import {
      AstroSkill,
      CSSSkill,
      FastAPISkill,
      HTMLSkill,
      JavascriptSkill,
      NetlifySkill,
      PostgreSQLSkill,
      PyTestSkill,
      PythonSkill,
      RailwaySkill,
      ReactSkill,
      RenderSkill,
      SQLiteSkill,
      TailwindCSSSkill,
      TypescriptSkill,
      VercelSkill,
  } from "@/components/skills";

  import styles from "./Main.module.css";
</script>

<div class={styles.section}>
  <h2 class={styles.sectionHeading}>Technologies</h2>
  <div class="flex flex-col gap-2">
    <h3 class="min-w-30 font-semibold">Frontend</h3>
    <div class="flex flex-wrap gap-2">
      <HTMLSkill />
      <CSSSkill />
      <JavascriptSkill />
      <TypescriptSkill />
      <ReactSkill />
      <AstroSkill />
      <TailwindCSSSkill />
    </div>
  </div>
  <div class="flex flex-col gap-2">
    <h3 class="min-w-30 font-semibold">Backend</h3>
    <div class="flex flex-wrap gap-2">
      <PythonSkill />
      <FastAPISkill />
      <PostgreSQLSkill />
      <SQLiteSkill />
      <PyTestSkill />
    </div>
  </div>
  <div class="flex flex-col gap-2">
    <h3 class="min-w-30 font-semibold">Deployment</h3>
    <div class="flex flex-wrap gap-2">
      <VercelSkill />
      <NetlifySkill />
      <RenderSkill />
      <RailwaySkill />
    </div>
  </div>
</div>
