// svelte-astro/src/components/header/contacts.svelte
<script>
  import { GithubIcon, GmailIcon } from "@/components/icons";
  import { Button } from "@/lib/components/ui/button";
</script>

<Button size="lg" href="https://github.com/mrdsx" target="_blank">
  <GithubIcon class="size-5" />
</Button>
<Button size="lg" href="mailto:kingofakneser@gmail.com">
  <GmailIcon class="size-5" />
</Button>

// react-astro/src/components/header/contacts.tsx
import GithubIcon from "@/components/icons/github";
import GmailIcon from "@/components/icons/gmail";
import { Button } from "@/components/ui/button";

const Contacts = () => (
  <>
    <Button size="lg" asChild>
      <a href="https://github.com/mrdsx" target="_blank">
        <GithubIcon className="size-5" />
      </a>
    </Button>
    <Button size="lg" asChild>
      <a href="mailto:kingofakneser@gmail.com">
        <GmailIcon className="size-5" />
      </a>
    </Button>
  </>
);

export default Contacts;
